[package]
name = "computing_project"
version = "0.1.0"
authors = ["= <=>"]
edition = "2018"

[dependencies]
num-integer = "0.1"
rayon = "1.1"
#numeric_literals = "0.1.0"
#flint = { path = "./flint-rust/" }

[profile.release]
#debug = true